#ifndef _RWCOMM_VERSION
#define _RWCOMM_VERSION

#include "rwversion.h"


#define RW_GET_VERSION(version)           ( ( RWLIBRARYIDUNPACKVERSION(version) & 0xF0000) >> 16 )
#define RW_GET_MAJOR_REVISION(version)    ( ( RWLIBRARYIDUNPACKVERSION(version) & 0x0F000) >> 12 )
#define RW_GET_MINOR_REVISION(version)    ( ( RWLIBRARYIDUNPACKVERSION(version) & 0x00F00) >> 8 )
#define RW_GET_BINARY_REVISION(version)   ( RWLIBRARYIDUNPACKVERSION(version) & 0x000FF)
#define RW_GET_BUILD_NUMBER(version)      ( RWLIBRARYIDUNPACKBUILDNUM(version) )

#define RW_VERSION RWLIBRARYIDPACK(rwLIBRARYCURRENTVERSION, RWBUILDNUMBER)
#define RW_VERSION_STRING   rwLIBRARYCURRENTRWVERSION , rwLIBRARYCURRENTMAJORREVISION , rwLIBRARYCURRENTMINORREVISION , rwLIBRARYCURRENTBINARYREVISION
#define RW_FULL_VERSION_STRING   rwLIBRARYCURRENTRWVERSION , rwLIBRARYCURRENTMAJORREVISION , rwLIBRARYCURRENTMINORREVISION , rwLIBRARYCURRENTBINARYREVISION , RWBUILDNUMBER


#define RW_VERSION_IGNORE   0xFFFFFFFFU
#define RW_VERSION_FUNC     "RwGetVersion"

extern "C"
{


__declspec(dllexport) unsigned long RwGetVersion()
{
    return RW_VERSION;
}

};

#if !defined(_CPPRTTI)
#error OpenExport plugins must be compiled with RTTI
#endif // !defined(_CPPRTTI)

#endif // _RWCOMM_VERSION
